[package]
name = "utu_relay"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.2"
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.20.0" }
openzeppelin_upgrades = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.20.0" }
utils = { git = "https://github.com/keep-starknet-strange/raito.git", rev = "02a13045b7074ae2b3247431cd91f1ad76263fb2" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.36.0" }

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true

[lib]
sierra = true
casm = false

[cairo]
sierra-replace-ids = true
